version: '3.7'
services:
  sardine:
    container_name: sardine
    build:
      context: .
      dockerfile: Dockerfile
      #target: dev
    restart: always
    command: tail -F null
    stdin_open: true
    ports:
      - "23000:23000"