name: Build Wheels YAay

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Clone python-rtmidi
        uses: actions/checkout@v3
        with:
          name:  https://github.com/SpotlightKid/python-rtmidi.git
          repository: SpotlightKid/python-rtmidi
          # /home/runner/work/sardine/sardine
          path: ./python-rtmidi
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.10.2
      # Make ls in the current directory
      - name: List files
        run: ls python-rtmidi
      - name: Build wheels
        # 
        run : cd python-rtmidi && pip install Cython && python -m cibuildwheel --output-dir wheelhouse
        #run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
          env:
            CIBW_BEFORE_BUILD="cd src/sib/c_package; python setup.py build_ext --inplace"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl


